### ISSUE TITLE
Bazel’ rules use platforms to select toolchains

### ISSUE THREAD

**Issue by peter197321** [mjbots/rpi_bazel#5]
Are you planning to update for use of `--platforms` instead of the legacy `--crosstool_top` as indicated in [Building with platforms in C++](https://docs.bazel.build/versions/master/platforms-intro.html#c)

Thank you.

**Comment by jpieper** [comment]
I would like to.  I actually spent about a day trying with bazel 2.0, however the platform support for C++ was still pretty weak then and making something work was going to take more effort than that by a lot.  I've been following the changelog and haven't seen significant improvements since then so am mostly waiting.

The biggest challenge was that for rpi_bazel I compile the c++ standard library and then link it.  Right now, you have to manually list the standard library as a dependency for binaries.  I was planning on waiting to switch until I could drop that requirement.

**Comment by peter197321** [comment]
hmm there is already

c:\>bazel --version
*bazel 3.2.0*

I am looking into your repo learn from it how to cross-compile :)

Good job!

**Comment by jpieper** [comment]
Yes, I know.  But none of the releases between 2 and 3.2 claim to have done much of anything to improve the C++ platform experience, and all the relevant issues show no progress.

**Comment by beautifulnight** [comment]
Is it still planned? 
I am learning how to use Bazel to cross-compile a Linux-arm binary on a windows x64 machine and this repo is close to my purpose.

**Comment by jpieper** [comment]
Nope, sorry, it is not planned any more.
